### ISSUE TITLE
FSD: shared folder refactor

### ISSUE THREAD

**Issue by NikitaStarmoussov** [rolling-scopes/site#345]
## 📝 Describe the refactoring task

Shared folder refactor

## 📍 Code location

"@/shared/"

## 🛠️ Suggested improvement

["Example" PR](https://github.com/rolling-scopes/site/pull/350)
[Презентация по FSD](https://docs.google.com/presentation/d/13prCFUxcrIaZg8-YwSKHj7BEwuYmEg7sCPTKTcPgO18/edit?usp=sharing)

## ✅ Definition of Done (DoD):

Everything on the list has been refactored

## TO-DO

1) UI:

- [x]  actions #430 @ansivgit 
- [x] date-lang #372 @Wystov 
- [x]  image #452 , @Quiddlee 
- [x]  link-cusom #370, @alextes90 
- [x]  logo-wrapper #368 , @MielomankA 
- [x]  paragraph: #355, @seygorin 
- [x]  section-label #376, @seygorin 
- [x]  social-media #448  @ansivgit 
- [x]  subtitle #375, @seygorin 
- [x]  ~text-with-link - should be deleted~ - decided to perform separately as its own issue
- [x]  title: #348, @NikitaStarmoussov

~2) Data (related:~ - Data will be refactored separately as it's own milestone
- [x] #276 ,
- [ ] #450 

~3) Assets + icons~ - Assets decided to leave as it is, icons can be refactored separately but not yet necessary

~4) hooks: use-course-by-title, use-data-by-name, app/services/api~ - Part of the huge milestone for data refactor (data will be fetched from external CDN so this hooks will be deleted)

### update 26.08.24:

1. Icons from now on are imported directly into components where needed using the image component, no need to create icons wrapper e.g. [icons folder](https://github.com/rolling-scopes/site/tree/main/src/shared/icons)
2. `"3. Assets + icons"` and `"4. hooks: use-course-by-title, use-data-by-name, app/services/api"`- decided to exclude from FSD refactor and expected to perform as a separate issues after we fully complete the migration
